### ISSUE TITLE
Audit of README.md

### ISSUE THREAD

**Issue by F-said** [NDCLab/pepper-pipeline#207]
**What needs documentation and what will each item entail?**
Audit to check:

- Does README.md provide all the information required for an external user to understand how to use pipeline and how it works. - is the README succint?

**Comment by jessb0t** [comment]
@F-said
I pushed my suggested changes to `dev-readme-jess` branch.  This version of the .md file includes notes marked:

__________________FROM JESS
This is a note from me!
__________________FROM JESS

Please be aware that I tried to edit for clarity, but it is very likely that I might have misunderstood the techniques and therefore some edits might be invalid, so they should be reviewed carefully and taken with the grain of salt with which they were intended!  (As an example, I assumed that "segment/epoch" meant "segment by epoch," which I thought was more clear to a novice reader...but maybe it doesn't mean that at all!

In the pipeline steps section, you specified which field is populated in the output file for several of the write steps.  I added (field "XXX") to the lines where this information is missing so that we have a consistent, clear explanation.  But, obviously, we need information to fill in those X's. :)

At the end, I pasted in some of the new, default content for our readmes, including the table of contributors; but it's blank right now since I don't know how best to record the project contributors!

Is this going to get pushed to main?  Just note that the current lingo on the readme (that is, the default bits that I pasted in) implies that one is already looking at main...

Feel free to let me know if you'd like me to take another look once you've had the chance to digest my comments and suggestions! 🤠

**Comment by F-said** [comment]
Thanks @jessb0t!

**Comment by F-said** [comment]
resolved
